services:
  - type: worker
    name: hibiny-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_bot.py
    envVars:
      - key: TOKEN
        value: 8534033828:AAHSPqujxmfLjcKw-551GrYEt2j8Hj92IzQ
      - key: MANAGER_CHAT_ID
        value: 6091836352
      - key: INSTRUCTORS_CHAT_ID
        value: -1003431251566
      - key: GUIDES_CHAT_ID
        value: -1003489190945
      - key: YANDEX_API_KEY
        value: AQVN3CC1HUcTfvTOOksgIt6aTiqwcDu6XMXVIdD7
      - key: YANDEX_FOLDER_ID
        value: b1gn044gg670ik0d5iev
      - key: YOOKASSA_SHOP_ID
        value: 1449585
      - key: YOOKASSA_SECRET_KEY
        value: live_CIyiH3YFeNYsQYFiD0i5MufPwkqwwUj8_85PrVX3EKo