from enum import Enum

class StateData:
    """Класс для хранения данных состояния пользователя"""
    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)
    
    def to_dict(self):
        """Преобразует объект в словарь"""
        return {key: value for key, value in self.__dict__.items() if not key.startswith('_')}
    
    @classmethod
    def from_dict(cls, data_dict):
        """Создает объект из словаря"""
        return cls(**data_dict)

class UserStates(Enum):
    MAIN_MENU = 'main_menu'
    WRITE_MANAGER = 'write_manager'
    
    # Отель
    HOTEL_START = 'hotel_start'
    HOTEL_SELECT_CHECKIN = 'hotel_select_checkin'
    HOTEL_SELECT_CHECKOUT = 'hotel_select_checkout'
    HOTEL_ENTER_NAME = 'hotel_enter_name'
    HOTEL_ENTER_PHONE = 'hotel_enter_phone'
    HOTEL_CONFIRMATION = 'hotel_confirmation'
    
    # Инструкторы
    INSTRUCTORS_START = 'instructors_start'
    INSTRUCTORS_SELECT_SPORT = 'instructors_select_sport'
    INSTRUCTORS_ENTER_OTHER_SPORT = 'instructors_enter_other_sport'
    INSTRUCTORS_PROGRAM_INFO = 'instructors_program_info'
    INSTRUCTORS_SELECT_PROGRAM = 'instructors_select_program'
    INSTRUCTORS_SELECT_PEOPLE = 'instructors_select_people'
    INSTRUCTORS_CHILDREN_INFO = 'instructors_children_info'
    INSTRUCTORS_SELECT_TYPE = 'instructors_select_type'
    INSTRUCTORS_ENTER_GROUP_SIZE = 'instructors_enter_group_size'
    INSTRUCTORS_FREERIDE_LEVEL = 'instructors_freeride_level'
    INSTRUCTORS_SELECT_STUDENT = 'instructors_select_student'
    INSTRUCTORS_SELECT_HOURS = 'instructors_select_hours'
    INSTRUCTORS_FREERIDE_DURATION = 'instructors_freeride_duration'
    INSTRUCTORS_FREERIDE_DAYS = 'instructors_freeride_days'
    INSTRUCTORS_SELECT_GROUP_SLOT = 'instructors_select_group_slot'
    INSTRUCTORS_ENTER_DATE = 'instructors_enter_date'
    INSTRUCTORS_ENTER_TIME = 'instructors_enter_time'
    INSTRUCTORS_ENTER_NAME = 'instructors_enter_name'
    INSTRUCTORS_ENTER_PHONE = 'instructors_enter_phone'
    INSTRUCTORS_ENTER_NOTE = 'instructors_enter_note'
    INSTRUCTORS_CONFIRMATION = 'instructors_confirmation'
    INSTRUCTOR_MODIFY_OFFER = 'instructor_modify_offer'
    INSTRUCTOR_MY_BOOKINGS = 'instructor_my_bookings'
    INSTRUCTOR_RESCHEDULE_DATE = 'instructor_reschedule_date'
    INSTRUCTOR_RESCHEDULE_TIME = 'instructor_reschedule_time'
    
    # Экскурсии (клиент)
    EXCURSIONS_START = 'excursions_start'
    EXCURSIONS_SELECT = 'excursions_select'
    EXCURSIONS_VIEW_DETAILS = 'excursions_view_details'
    EXCURSIONS_ENTER_DATE = 'excursions_enter_date'
    EXCURSIONS_ENTER_PEOPLE = 'excursions_enter_people'
    EXCURSIONS_ENTER_NAME = 'excursions_enter_name'
    EXCURSIONS_ENTER_PHONE = 'excursions_enter_phone'
    EXCURSIONS_ENTER_NOTE = 'excursions_enter_note'
    EXCURSIONS_CONFIRMATION = 'excursions_confirmation'
    EXCURSIONS_OTHER = 'excursions_other'
    EXCURSIONS_OTHER_INPUT = 'excursions_other_input'
    EXCURSIONS_CHILDREN_INFO = 'excursions_children_info'
    EXCURSIONS_GROUP_SELECT = 'excursions_group_select'
    EXCURSIONS_VIEW_GROUP = 'excursions_view_group'
    EXCURSIONS_JOIN_GROUP = 'excursions_join_group'
    
    # Гиды
    GUIDE_MAKE_OFFER = 'guide_make_offer'
    GUIDE_CREATE_START = 'guide_create_start'
    GUIDE_CREATE_NAME = 'guide_create_name'
    GUIDE_CREATE_DESCRIPTION = 'guide_create_description'
    GUIDE_CREATE_PHOTO = 'guide_create_photo'
    GUIDE_CREATE_PRICE = 'guide_create_price'
    GUIDE_CREATE_MIN_PEOPLE = 'guide_create_min_people'
    GUIDE_CREATE_MAX_PEOPLE = 'guide_create_max_people'
    GUIDE_CREATE_DURATION = 'guide_create_duration'
    GUIDE_CREATE_DATES = 'guide_create_dates'
    GUIDE_CREATE_TIMES = 'guide_create_times'
    GUIDE_CREATE_CONFIRMATION = 'guide_create_confirmation'
    GUIDE_MODIFY_OFFER = 'guide_modify_offer'
    GUIDE_OFFER_CREATE = 'guide_offer_create'
    GUIDE_MY_BOOKINGS = 'guide_my_bookings'
    GUIDE_RESCHEDULE_DATE = 'guide_reschedule_date'
    GUIDE_RESCHEDULE_TIME = 'guide_reschedule_time'
    GUIDE_CREATE_LOCATION = 'guide_create_location'
    GUIDE_CREATE_RULES = 'guide_create_rules'
    GUIDE_CREATE_NOTE = 'guide_create_note'
    GUIDE_MODIFY_MIN_PEOPLE = 'guide_modify_min_people'
    GUIDE_MODIFY_MAX_PEOPLE = 'guide_modify_max_people'
    
    # Магазин
    SHOP_START = 'shop_start'
    SHOP_CATEGORIES = 'shop_categories'
    SHOP_PRODUCTS = 'shop_products'
    SHOP_PRODUCT_DETAILS = 'shop_product_details'
    SHOP_ENTER_QUANTITY = 'shop_enter_quantity'
    SHOP_ENTER_ADDRESS = 'shop_enter_address'
    SHOP_CONFIRMATION = 'shop_confirmation'
    
    # Экспедиции
    EXPEDITIONS_START = 'expeditions_start'
    EXPEDITIONS_SELECT = 'expeditions_select'
    EXPEDITIONS_VIEW_DETAILS = 'expeditions_view_details'
    EXPEDITIONS_ENTER_NAME = 'expeditions_enter_name'
    EXPEDITIONS_ENTER_PEOPLE = 'expeditions_enter_people'
    EXPEDITIONS_ENTER_PHONE = 'expeditions_enter_phone'
    EXPEDITIONS_ENTER_WISHES = 'expeditions_enter_wishes'
    EXPEDITIONS_CONFIRMATION = 'expeditions_confirmation'
    
    # Мои заказы (клиент)
    ORDERS_LIST = 'orders_list'
    ORDER_DETAILS = 'order_details'
    ORDER_RESCHEDULE_DATE = 'order_reschedule_date'
    ORDER_RESCHEDULE_TIME = 'order_reschedule_time'
    
    # Админка
    ADMIN_MAIN = 'admin_main'
    ADMIN_HOTEL = 'admin_hotel'
    ADMIN_BLOCK_DATE = 'admin_block_date'
    ADMIN_UNBLOCK_DATE = 'admin_unblock_date'
    ADMIN_CANCEL_BOOKING = 'admin_cancel_booking'
    ADMIN_INSTRUCTORS = 'admin_instructors'
    ADMIN_PRICE_SETTINGS = 'admin_price_settings'
    ADMIN_SET_PRICE_BASE = 'admin_set_price_base'
    ADMIN_SET_PRICE_CHILD = 'admin_set_price_child'
    ADMIN_SET_PRICE_FREERIDE = 'admin_set_price_freeride'
    ADMIN_SET_PRICE_CARVING = 'admin_set_price_carving'
    ADMIN_SET_DISCOUNT_GROUP = 'admin_set_discount_group'
    ADMIN_SET_COMMISSION = 'admin_set_commission'
    ADMIN_INSTRUCTOR_STATS = 'admin_instructor_stats'
    ADMIN_EXCURSIONS = 'admin_excursions'
    ADMIN_ADD_EXCURSION_NAME = 'admin_add_excursion_name'
    ADMIN_ADD_EXCURSION_DESC = 'admin_add_excursion_desc'
    ADMIN_ADD_EXCURSION_PRICE = 'admin_add_excursion_price'
    ADMIN_ADD_EXCURSION_MIN_PEOPLE = 'admin_add_excursion_min_people'
    ADMIN_ADD_EXCURSION_MAX_PEOPLE = 'admin_add_excursion_max_people'
    ADMIN_ADD_EXCURSION_DURATION = 'admin_add_excursion_duration'
    ADMIN_EDIT_EXCURSION = 'admin_edit_excursion'
    ADMIN_EDIT_EXCURSION_DETAILS = 'admin_edit_excursion_details'
    ADMIN_EXCURSION_PRICE_SETTINGS = 'admin_excursion_price_settings'
    ADMIN_SET_GUIDE_COMMISSION = 'admin_set_guide_commission'
    ADMIN_EXPEDITIONS = 'admin_expeditions'
    ADMIN_ADD_EXPEDITION_NAME = 'admin_add_expedition_name'
    ADMIN_ADD_EXPEDITION_DESC = 'admin_add_expedition_desc'
    ADMIN_ADD_EXPEDITION_PROGRAM = 'admin_add_expedition_program'
    ADMIN_ADD_EXPEDITION_INCLUDED = 'admin_add_expedition_included'
    ADMIN_ADD_EXPEDITION_PRICE = 'admin_add_expedition_price'
    ADMIN_ADD_EXPEDITION_START_DATE = 'admin_add_expedition_start_date'
    ADMIN_ADD_EXPEDITION_END_DATE = 'admin_add_expedition_end_date'
    ADMIN_ADD_EXPEDITION_MAX_PEOPLE = 'admin_add_expedition_max_people'
    ADMIN_EDIT_EXPEDITION = 'admin_edit_expedition'
    ADMIN_EDIT_EXPEDITION_DETAILS = 'admin_edit_expedition_details'
    ADMIN_CONFIRM_EXPEDITION_PAYMENT = 'admin_confirm_expedition_payment'
    ADMIN_SHOP = 'admin_shop'
    ADMIN_ADD_PRODUCT_NAME = 'admin_add_product_name'
    ADMIN_ADD_PRODUCT_TYPE = 'admin_add_product_type'
    ADMIN_ADD_PRODUCT_DESC = 'admin_add_product_desc'
    ADMIN_ADD_PRODUCT_PRICE = 'admin_add_product_price'
    ADMIN_ADD_PRODUCT_STOCK = 'admin_add_product_stock'
    ADMIN_ADD_PRODUCT_FILE_URL = 'admin_add_product_file_url'
    ADMIN_EDIT_PRODUCT = 'admin_edit_product'
    ADMIN_EDIT_PRODUCT_DETAILS = 'admin_edit_product_details'
    ADMIN_VIEW_ORDERS = 'admin_view_orders'
    ADMIN_STATISTICS = 'admin_statistics'
    ADMIN_BROADCAST = 'admin_broadcast'
    ADMIN_CREATE_BROADCAST_TEXT = 'admin_create_broadcast_text'
    ADMIN_CREATE_BROADCAST_CONFIRM = 'admin_create_broadcast_confirm'
    ADMIN_CREATE_PROMO_NAME = 'admin_create_promo_name'
    ADMIN_CREATE_PROMO_DESC = 'admin_create_promo_desc'
    ADMIN_CREATE_PROMO_PRICE = 'admin_create_promo_price'
    ADMIN_CREATE_PROMO_DATES = 'admin_create_promo_dates'
    ADMIN_CREATE_PROMO_CONFIRM = 'admin_create_promo_confirm'